# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algemenekosten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ODE_per_kw_inclBTW', models.FloatField()),
                ('ODE_per_m3_inclBTW', models.FloatField()),
                ('energiebelasting_per_kw_inclBTW', models.FloatField()),
                ('energiebelasting_per_m3_inclBTW', models.FloatField()),
                ('BTW', models.FloatField(max_length=10)),
                ('heffingskorting_elektriciteit', models.FloatField()),
                ('jaar', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Kosten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gasprijs_per_m3', models.FloatField()),
                ('prijs_per_Kw', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Leveranciers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Netbeheerderkosten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capaciteitstarief_elektriciteit_25A_onbemeten_per_jaar', models.FloatField()),
                ('capaciteitstarief_elektriciteit_25A_bemeten_per_jaar', models.FloatField()),
                ('capaciteitstarief_gas', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Netbeheerders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='netbeheerderkosten',
            name='netbeheerder',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bereken.Netbeheerders'),
        ),
        migrations.AddField(
            model_name='kosten',
            name='leverancier',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bereken.Leveranciers'),
        ),
    ]
