# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bereken', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kosten',
            name='vastrecht',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
