# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bereken', '0003_auto_20160223_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='kosten',
            name='regiotoeslag_gas',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
